server:
  port: 9000
  servlet:
    context-path: /api/v1

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${db.url}:3306/simple_shopping_mall?serverTimezone=Asia/Seoul
    username: ${db.username}
    password: ${db.password}

  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
      format-sql: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  web:
    resources:
      static-locations: /static/**

jwt:
  secret: random_abcd
